"""stock_history_update

Revision ID: 1679005d7175
Revises: 970f40e163af
Create Date: 2025-09-22 12:21:08.771853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1679005d7175'
down_revision: Union[str, None] = '970f40e163af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_histories',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('operation', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('operation_name', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('last_updated', sa.DATE(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['stock_id'], ['stock_managments.id'], name='stock_managments_history_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='stock_histories_pkey')
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('stock_histories')
