"""update_history

Revision ID: 454a08f68a12
Revises: b3ccc098aa59
Create Date: 2025-09-22 12:46:10.860718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454a08f68a12'
down_revision: Union[str, None] = 'b3ccc098aa59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_histories', sa.Column('owner_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'stock_histories', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('operation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('operation_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_updated', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock_managments.id'], name='stock_managments_history_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stock_histories_pkey')
    )
    # ### end Alembic commands ###
