"""add_operator_name_on_stocks

Revision ID: 7858bd8c72a4
Revises: 803864de0f06
Create Date: 2025-09-09 20:58:41.816990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7858bd8c72a4'
down_revision: Union[str, None] = '803864de0f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employees_email_key', 'employees', type_='unique')
    op.drop_constraint('employees_username_key', 'employees', type_='unique')
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)

    op.create_table('stock_histories',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('operation', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('operation_name', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('last_updated', sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(['stock_id'], ['stock_managments.id'], name='stock_managments_history_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='stock_histories_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.create_unique_constraint('employees_username_key', 'employees', ['username'])
    op.create_unique_constraint('employees_email_key', 'employees', ['email'])
    # ### end Alembic commands ###
