"""stock_update

Revision ID: 970f40e163af
Revises: 7858bd8c72a4
Create Date: 2025-09-22 11:43:28.338505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970f40e163af'
down_revision: Union[str, None] = '7858bd8c72a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_histories')
    
    # Ajout de la colonne owner_id avant la contrainte
    op.add_column('stock_managments', sa.Column('owner_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'stock_managments', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_managments', type_='foreignkey')
    op.drop_column('stock_managments', 'owner_id')
    op.create_table('stock_histories',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('operation', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('operation_name', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('last_updated', sa.DATE(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['stock_id'], ['stock_managments.id'], name='stock_managments_history_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='stock_histories_pkey')
    )
    # ### end Alembic commands ###
