"""update_stock_and_employee

Revision ID: b3ccc098aa59
Revises: 1679005d7175
Create Date: 2025-09-22 12:34:56.915349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b3ccc098aa59'
down_revision: Union[str, None] = '1679005d7175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('salary', sa.Float(), nullable=True))
    op.add_column('stock_managments', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_managments', 'category')
    op.drop_column('employees', 'salary')
    op.create_table('stock_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('operation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('operation_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_updated', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock_managments.id'], name='stock_managments_history_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stock_histories_pkey')
    )
    # ### end Alembic commands ###
